generatorName: r
inputSpec: azmet.yaml
library: httr2
additionalProperties:
  packageName: azmet
  packageVersion: 0.1.0
  packageLicense: MIT
  packageRepository: https://github.com/cct-datascience/azmet-r
  exceptionPackage: rlang
  useRlangExceptionHandling: true
  returnExceptionOnFailure: true
  errorObjectType: "ModelApiResponse"
  operationIdNaming: snake_case
