# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2003DataInner")

model_instance <- InlineResponse2003DataInner$new()

test_that("date_year", {
  # tests for the property `date_year` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_year`, "EXPECTED_RESULT")
})

test_that("precip_total", {
  # tests for the property `precip_total` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`precip_total`, "EXPECTED_RESULT")
})

test_that("meta_version", {
  # tests for the property `meta_version` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_version`, "EXPECTED_RESULT")
})

test_that("wind_spd_max_mph", {
  # tests for the property `wind_spd_max_mph` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_spd_max_mph`, "EXPECTED_RESULT")
})

test_that("date_datetime", {
  # tests for the property `date_datetime` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_datetime`, "EXPECTED_RESULT")
})

test_that("wind_vector_dir", {
  # tests for the property `wind_vector_dir` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_vector_dir`, "EXPECTED_RESULT")
})

test_that("wind_spd_mps", {
  # tests for the property `wind_spd_mps` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_spd_mps`, "EXPECTED_RESULT")
})

test_that("heatstress_cottonC", {
  # tests for the property `heatstress_cottonC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`heatstress_cottonC`, "EXPECTED_RESULT")
})

test_that("meta_station_id", {
  # tests for the property `meta_station_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_station_id`, "EXPECTED_RESULT")
})

test_that("date_doy", {
  # tests for the property `date_doy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_doy`, "EXPECTED_RESULT")
})

test_that("vp_actual", {
  # tests for the property `vp_actual` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`vp_actual`, "EXPECTED_RESULT")
})

test_that("temp_airF", {
  # tests for the property `temp_airF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_airF`, "EXPECTED_RESULT")
})

test_that("wind_spd_mph", {
  # tests for the property `wind_spd_mph` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_spd_mph`, "EXPECTED_RESULT")
})

test_that("temp_airC", {
  # tests for the property `temp_airC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_airC`, "EXPECTED_RESULT")
})

test_that("eto_azmet_in", {
  # tests for the property `eto_azmet_in` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eto_azmet_in`, "EXPECTED_RESULT")
})

test_that("heatstress_cottonF", {
  # tests for the property `heatstress_cottonF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`heatstress_cottonF`, "EXPECTED_RESULT")
})

test_that("sol_rad_total", {
  # tests for the property `sol_rad_total` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sol_rad_total`, "EXPECTED_RESULT")
})

test_that("meta_bat_volt", {
  # tests for the property `meta_bat_volt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_bat_volt`, "EXPECTED_RESULT")
})

test_that("precip_total_in", {
  # tests for the property `precip_total_in` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`precip_total_in`, "EXPECTED_RESULT")
})

test_that("meta_needs_review", {
  # tests for the property `meta_needs_review` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_needs_review`, "EXPECTED_RESULT")
})

test_that("sol_rad_total_ly", {
  # tests for the property `sol_rad_total_ly` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sol_rad_total_ly`, "EXPECTED_RESULT")
})

test_that("eto_azmet", {
  # tests for the property `eto_azmet` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eto_azmet`, "EXPECTED_RESULT")
})

test_that("wind_vector_magnitude_mph", {
  # tests for the property `wind_vector_magnitude_mph` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_vector_magnitude_mph`, "EXPECTED_RESULT")
})

test_that("date_hour", {
  # tests for the property `date_hour` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_hour`, "EXPECTED_RESULT")
})

test_that("temp_soil_10cmF", {
  # tests for the property `temp_soil_10cmF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_10cmF`, "EXPECTED_RESULT")
})

test_that("wind_vector_dir_stand_dev", {
  # tests for the property `wind_vector_dir_stand_dev` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_vector_dir_stand_dev`, "EXPECTED_RESULT")
})

test_that("vp_deficit", {
  # tests for the property `vp_deficit` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`vp_deficit`, "EXPECTED_RESULT")
})

test_that("wind_spd_max_mps", {
  # tests for the property `wind_spd_max_mps` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_spd_max_mps`, "EXPECTED_RESULT")
})

test_that("dwptF", {
  # tests for the property `dwptF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`dwptF`, "EXPECTED_RESULT")
})

test_that("dwpt", {
  # tests for the property `dwpt` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`dwpt`, "EXPECTED_RESULT")
})

test_that("wind_vector_magnitude", {
  # tests for the property `wind_vector_magnitude` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_vector_magnitude`, "EXPECTED_RESULT")
})

test_that("meta_station_name", {
  # tests for the property `meta_station_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_station_name`, "EXPECTED_RESULT")
})

test_that("temp_soil_50cmC", {
  # tests for the property `temp_soil_50cmC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_50cmC`, "EXPECTED_RESULT")
})

test_that("relative_humidity", {
  # tests for the property `relative_humidity` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`relative_humidity`, "EXPECTED_RESULT")
})

test_that("temp_soil_10cmC", {
  # tests for the property `temp_soil_10cmC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_10cmC`, "EXPECTED_RESULT")
})

test_that("temp_soil_50cmF", {
  # tests for the property `temp_soil_50cmF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_50cmF`, "EXPECTED_RESULT")
})
