# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2005DataInner")

model_instance <- InlineResponse2005DataInner$new()

test_that("heat_units_55F_sum", {
  # tests for the property `heat_units_55F_sum` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`heat_units_55F_sum`, "EXPECTED_RESULT")
})

test_that("heat_units_50F_sum", {
  # tests for the property `heat_units_50F_sum` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`heat_units_50F_sum`, "EXPECTED_RESULT")
})

test_that("eto_pen_mon_in_sum", {
  # tests for the property `eto_pen_mon_in_sum` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`eto_pen_mon_in_sum`, "EXPECTED_RESULT")
})

test_that("eto_azmet_in", {
  # tests for the property `eto_azmet_in` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eto_azmet_in`, "EXPECTED_RESULT")
})

test_that("eto_azmet_in_sum", {
  # tests for the property `eto_azmet_in_sum` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`eto_azmet_in_sum`, "EXPECTED_RESULT")
})

test_that("precip_total_in", {
  # tests for the property `precip_total_in` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`precip_total_in`, "EXPECTED_RESULT")
})

test_that("eto_pen_mon_in", {
  # tests for the property `eto_pen_mon_in` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eto_pen_mon_in`, "EXPECTED_RESULT")
})

test_that("meta_station_id", {
  # tests for the property `meta_station_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_station_id`, "EXPECTED_RESULT")
})

test_that("meta_station_name", {
  # tests for the property `meta_station_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_station_name`, "EXPECTED_RESULT")
})

test_that("precip_total_in_sum", {
  # tests for the property `precip_total_in_sum` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`precip_total_in_sum`, "EXPECTED_RESULT")
})

test_that("datetime_last", {
  # tests for the property `datetime_last` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`datetime_last`, "EXPECTED_RESULT")
})

test_that("heat_units_45F_sum", {
  # tests for the property `heat_units_45F_sum` (numeric)

  # uncomment below to test the property
  #expect_equal(model.instance$`heat_units_45F_sum`, "EXPECTED_RESULT")
})
