# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test HourlyApi")

api_instance <- HourlyApi$new()

test_that("V1ObservationsHourlyGet", {
  # tests for V1ObservationsHourlyGet
  # base path: https://api.azmet.arizona.edu
  # Pull hourly direct and derived observations for all stations over the last 24 hours.
  # @return [InlineResponse2002]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1ObservationsHourlyStationIDDateTimeStartGet", {
  # tests for V1ObservationsHourlyStationIDDateTimeStartGet
  # base path: https://api.azmet.arizona.edu
  # Return hourly direct and derived observations for a specific station and date and time.
  # Pull hourly direct and derived observations for a specific station over the last 24 hours starting at a particular date and time.
  # @param station_id character ID of station
  # @param date_time_start character Date and time of data request start
  # @return [InlineResponse2003]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1ObservationsHourlyStationIDDateTimeStartTimeIntervalGet", {
  # tests for V1ObservationsHourlyStationIDDateTimeStartTimeIntervalGet
  # base path: https://api.azmet.arizona.edu
  # Return hourly direct and derived observations for a specific station over a time interval from a date and time.
  # Return hourly direct and derived observations for a specific station over a particular time interval starting at a particular date and time.
  # @param station_id character ID of station
  # @param date_time_start character Date and time of data request start
  # @param time_interval character ID of station
  # @return [InlineResponse2004]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1ObservationsHourlyStationIDGet", {
  # tests for V1ObservationsHourlyStationIDGet
  # base path: https://api.azmet.arizona.edu
  # Return hourly direct and derived observations for a specific station.
  # Pull hourly direct and derived observations for a specific station over the last 24 hours.
  # @param station_id character ID of station
  # @return [InlineResponse2003]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
