# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test HuetoApi")

api_instance <- HuetoApi$new()

test_that("V1ObservationsHuetoGet", {
  # tests for V1ObservationsHuetoGet
  # base path: https://api.azmet.arizona.edu
  # Accumulated heat units and evapotranspiration for all stations from January 1 current year.
  # Returns accumulated heat units and evapotranspiration for all stations from the start of the current year.
  # @return [InlineResponse2005]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1ObservationsHuetoStationIDDateTimeStartGet", {
  # tests for V1ObservationsHuetoStationIDDateTimeStartGet
  # base path: https://api.azmet.arizona.edu
  # Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time to current date.
  # Returns accumulated heat units and evapotranspiration for one (or all \&quot;*\&quot;) station(s) from the given start date and time to current date.
  # @param station_id character ID of station
  # @param date_time_start character Date and time of data request start
  # @return [InlineResponse2006]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1ObservationsHuetoStationIDDateTimeStartTimeIntervalGet", {
  # tests for V1ObservationsHuetoStationIDDateTimeStartTimeIntervalGet
  # base path: https://api.azmet.arizona.edu
  # Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time over a given time interval.
  # Returns accumulated heat units and evapotranspiration for one (or all \&quot;*\&quot;) station(s) from the given start date and timeover a given time interval.
  # @param station_id character ID of station
  # @param date_time_start character Date and time of data request start
  # @param time_interval character The requested time interval
  # @return [InlineResponse2006]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1ObservationsHuetoStationIDGet", {
  # tests for V1ObservationsHuetoStationIDGet
  # base path: https://api.azmet.arizona.edu
  # Accumulated heat units and evapotranspiration for one station from January 1 current year.
  # Returns accumulated heat units and evapotranspiration for one station from the start of the current year.
  # @param station_id character ID of station
  # @return [InlineResponse2006]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
