# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test DailyApi")

api_instance <- DailyApi$new()

test_that("V1ObservationsDailyGet", {
  # tests for V1ObservationsDailyGet
  # base path: https://api.azmet.arizona.edu
  # Return daily direct and derived observations for all stations for the latest available day.
  # Returns available daily direct and derived observations for all stations for the latest available day.
  # @return [InlineResponse200]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1ObservationsDailyStationIDDateTimeStartGet", {
  # tests for V1ObservationsDailyStationIDDateTimeStartGet
  # base path: https://api.azmet.arizona.edu
  # Return daily direct and derived observations for a specific station and a specific date.
  # Returns available daily direct and derived observations for a specific station and a specific date.
  # @param station_id character ID of station
  # @param date_time_start character Date and time of data request start
  # @return [InlineResponse2001]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1ObservationsDailyStationIDDateTimeStartTimeIntervalGet", {
  # tests for V1ObservationsDailyStationIDDateTimeStartTimeIntervalGet
  # base path: https://api.azmet.arizona.edu
  # Return available daily direct and derived observations for a station over a time interval from a date.
  # Returns available daily direct and derived observations for a specific station over a time interval from a specific date.
  # @param station_id character ID of station
  # @param date_time_start character Datetime to start the interval
  # @param time_interval character The requested time interval
  # @return [InlineResponse2001]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("V1ObservationsDailyStationIDGet", {
  # tests for V1ObservationsDailyStationIDGet
  # base path: https://api.azmet.arizona.edu
  # Return daily direct and derived observations for a specific station.
  # Returns available daily direct and derived observations for a specific station.
  # @param station_id character ID of station
  # @return [InlineResponse2001]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})
