# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse200DataInner")

model_instance <- InlineResponse200DataInner$new()

test_that("chill_hours_0C", {
  # tests for the property `chill_hours_0C` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`chill_hours_0C`, "EXPECTED_RESULT")
})

test_that("chill_hours_20C", {
  # tests for the property `chill_hours_20C` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`chill_hours_20C`, "EXPECTED_RESULT")
})

test_that("chill_hours_32F", {
  # tests for the property `chill_hours_32F` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`chill_hours_32F`, "EXPECTED_RESULT")
})

test_that("chill_hours_45F", {
  # tests for the property `chill_hours_45F` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`chill_hours_45F`, "EXPECTED_RESULT")
})

test_that("chill_hours_68F", {
  # tests for the property `chill_hours_68F` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`chill_hours_68F`, "EXPECTED_RESULT")
})

test_that("chill_hours_7C", {
  # tests for the property `chill_hours_7C` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`chill_hours_7C`, "EXPECTED_RESULT")
})

test_that("date_doy", {
  # tests for the property `date_doy` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_doy`, "EXPECTED_RESULT")
})

test_that("date_year", {
  # tests for the property `date_year` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`date_year`, "EXPECTED_RESULT")
})

test_that("datetime", {
  # tests for the property `datetime` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`datetime`, "EXPECTED_RESULT")
})

test_that("dwpt_mean", {
  # tests for the property `dwpt_mean` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`dwpt_mean`, "EXPECTED_RESULT")
})

test_that("dwpt_meanF", {
  # tests for the property `dwpt_meanF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`dwpt_meanF`, "EXPECTED_RESULT")
})

test_that("eto_azmet", {
  # tests for the property `eto_azmet` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eto_azmet`, "EXPECTED_RESULT")
})

test_that("eto_azmet_in", {
  # tests for the property `eto_azmet_in` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eto_azmet_in`, "EXPECTED_RESULT")
})

test_that("eto_pen_mon", {
  # tests for the property `eto_pen_mon` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eto_pen_mon`, "EXPECTED_RESULT")
})

test_that("eto_pen_mon_in", {
  # tests for the property `eto_pen_mon_in` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`eto_pen_mon_in`, "EXPECTED_RESULT")
})

test_that("heat_units_10C", {
  # tests for the property `heat_units_10C` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`heat_units_10C`, "EXPECTED_RESULT")
})

test_that("heat_units_13C", {
  # tests for the property `heat_units_13C` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`heat_units_13C`, "EXPECTED_RESULT")
})

test_that("heat_units_3413C", {
  # tests for the property `heat_units_3413C` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`heat_units_3413C`, "EXPECTED_RESULT")
})

test_that("heat_units_45F", {
  # tests for the property `heat_units_45F` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`heat_units_45F`, "EXPECTED_RESULT")
})

test_that("heat_units_50F", {
  # tests for the property `heat_units_50F` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`heat_units_50F`, "EXPECTED_RESULT")
})

test_that("heat_units_55F", {
  # tests for the property `heat_units_55F` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`heat_units_55F`, "EXPECTED_RESULT")
})

test_that("heat_units_7C", {
  # tests for the property `heat_units_7C` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`heat_units_7C`, "EXPECTED_RESULT")
})

test_that("heat_units_9455F", {
  # tests for the property `heat_units_9455F` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`heat_units_9455F`, "EXPECTED_RESULT")
})

test_that("heatstress_cotton_meanC", {
  # tests for the property `heatstress_cotton_meanC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`heatstress_cotton_meanC`, "EXPECTED_RESULT")
})

test_that("heatstress_cotton_meanF", {
  # tests for the property `heatstress_cotton_meanF` (integer)

  # uncomment below to test the property
  #expect_equal(model.instance$`heatstress_cotton_meanF`, "EXPECTED_RESULT")
})

test_that("meta_bat_volt_max", {
  # tests for the property `meta_bat_volt_max` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_bat_volt_max`, "EXPECTED_RESULT")
})

test_that("meta_bat_volt_mean", {
  # tests for the property `meta_bat_volt_mean` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_bat_volt_mean`, "EXPECTED_RESULT")
})

test_that("meta_bat_volt_min", {
  # tests for the property `meta_bat_volt_min` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_bat_volt_min`, "EXPECTED_RESULT")
})

test_that("meta_needs_review", {
  # tests for the property `meta_needs_review` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_needs_review`, "EXPECTED_RESULT")
})

test_that("meta_station_id", {
  # tests for the property `meta_station_id` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_station_id`, "EXPECTED_RESULT")
})

test_that("meta_station_name", {
  # tests for the property `meta_station_name` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_station_name`, "EXPECTED_RESULT")
})

test_that("meta_version", {
  # tests for the property `meta_version` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`meta_version`, "EXPECTED_RESULT")
})

test_that("precip_total_mm", {
  # tests for the property `precip_total_mm` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`precip_total_mm`, "EXPECTED_RESULT")
})

test_that("precip_total_in", {
  # tests for the property `precip_total_in` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`precip_total_in`, "EXPECTED_RESULT")
})

test_that("relative_humidity_max", {
  # tests for the property `relative_humidity_max` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`relative_humidity_max`, "EXPECTED_RESULT")
})

test_that("relative_humidity_mean", {
  # tests for the property `relative_humidity_mean` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`relative_humidity_mean`, "EXPECTED_RESULT")
})

test_that("relative_humidity_min", {
  # tests for the property `relative_humidity_min` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`relative_humidity_min`, "EXPECTED_RESULT")
})

test_that("sol_rad_total", {
  # tests for the property `sol_rad_total` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sol_rad_total`, "EXPECTED_RESULT")
})

test_that("sol_rad_total_ly", {
  # tests for the property `sol_rad_total_ly` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`sol_rad_total_ly`, "EXPECTED_RESULT")
})

test_that("temp_air_maxC", {
  # tests for the property `temp_air_maxC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_air_maxC`, "EXPECTED_RESULT")
})

test_that("temp_air_maxF", {
  # tests for the property `temp_air_maxF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_air_maxF`, "EXPECTED_RESULT")
})

test_that("temp_air_meanC", {
  # tests for the property `temp_air_meanC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_air_meanC`, "EXPECTED_RESULT")
})

test_that("temp_air_meanF", {
  # tests for the property `temp_air_meanF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_air_meanF`, "EXPECTED_RESULT")
})

test_that("temp_air_minC", {
  # tests for the property `temp_air_minC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_air_minC`, "EXPECTED_RESULT")
})

test_that("temp_air_minF", {
  # tests for the property `temp_air_minF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_air_minF`, "EXPECTED_RESULT")
})

test_that("temp_soil_10cm_maxC", {
  # tests for the property `temp_soil_10cm_maxC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_10cm_maxC`, "EXPECTED_RESULT")
})

test_that("temp_soil_10cm_maxF", {
  # tests for the property `temp_soil_10cm_maxF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_10cm_maxF`, "EXPECTED_RESULT")
})

test_that("temp_soil_10cm_meanC", {
  # tests for the property `temp_soil_10cm_meanC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_10cm_meanC`, "EXPECTED_RESULT")
})

test_that("temp_soil_10cm_meanF", {
  # tests for the property `temp_soil_10cm_meanF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_10cm_meanF`, "EXPECTED_RESULT")
})

test_that("temp_soil_10cm_minC", {
  # tests for the property `temp_soil_10cm_minC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_10cm_minC`, "EXPECTED_RESULT")
})

test_that("temp_soil_10cm_minF", {
  # tests for the property `temp_soil_10cm_minF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_10cm_minF`, "EXPECTED_RESULT")
})

test_that("temp_soil_50cm_maxC", {
  # tests for the property `temp_soil_50cm_maxC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_50cm_maxC`, "EXPECTED_RESULT")
})

test_that("temp_soil_50cm_maxF", {
  # tests for the property `temp_soil_50cm_maxF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_50cm_maxF`, "EXPECTED_RESULT")
})

test_that("temp_soil_50cm_meanC", {
  # tests for the property `temp_soil_50cm_meanC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_50cm_meanC`, "EXPECTED_RESULT")
})

test_that("temp_soil_50cm_meanF", {
  # tests for the property `temp_soil_50cm_meanF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_50cm_meanF`, "EXPECTED_RESULT")
})

test_that("temp_soil_50cm_minC", {
  # tests for the property `temp_soil_50cm_minC` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_50cm_minC`, "EXPECTED_RESULT")
})

test_that("temp_soil_50cm_minF", {
  # tests for the property `temp_soil_50cm_minF` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`temp_soil_50cm_minF`, "EXPECTED_RESULT")
})

test_that("vp_actual_max", {
  # tests for the property `vp_actual_max` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`vp_actual_max`, "EXPECTED_RESULT")
})

test_that("vp_actual_mean", {
  # tests for the property `vp_actual_mean` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`vp_actual_mean`, "EXPECTED_RESULT")
})

test_that("vp_actual_min", {
  # tests for the property `vp_actual_min` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`vp_actual_min`, "EXPECTED_RESULT")
})

test_that("vp_deficit_mean", {
  # tests for the property `vp_deficit_mean` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`vp_deficit_mean`, "EXPECTED_RESULT")
})

test_that("wind_spd_max_mph", {
  # tests for the property `wind_spd_max_mph` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_spd_max_mph`, "EXPECTED_RESULT")
})

test_that("wind_spd_max_mps", {
  # tests for the property `wind_spd_max_mps` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_spd_max_mps`, "EXPECTED_RESULT")
})

test_that("wind_spd_mean_mph", {
  # tests for the property `wind_spd_mean_mph` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_spd_mean_mph`, "EXPECTED_RESULT")
})

test_that("wind_spd_mean_mps", {
  # tests for the property `wind_spd_mean_mps` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_spd_mean_mps`, "EXPECTED_RESULT")
})

test_that("wind_vector_dir", {
  # tests for the property `wind_vector_dir` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_vector_dir`, "EXPECTED_RESULT")
})

test_that("wind_vector_dir_stand_dev", {
  # tests for the property `wind_vector_dir_stand_dev` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_vector_dir_stand_dev`, "EXPECTED_RESULT")
})

test_that("wind_vector_magnitude", {
  # tests for the property `wind_vector_magnitude` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_vector_magnitude`, "EXPECTED_RESULT")
})

test_that("wind_vector_magnitude_mph", {
  # tests for the property `wind_vector_magnitude_mph` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`wind_vector_magnitude_mph`, "EXPECTED_RESULT")
})
