# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test InlineResponse2005")

model_instance <- InlineResponse2005$new()

test_that("data", {
  # tests for the property `data` (array[InlineResponse2005DataInner])

  # uncomment below to test the property
  #expect_equal(model.instance$`data`, "EXPECTED_RESULT")
})

test_that("errors", {
  # tests for the property `errors` (array[character])

  # uncomment below to test the property
  #expect_equal(model.instance$`errors`, "EXPECTED_RESULT")
})

test_that("i", {
  # tests for the property `i` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`i`, "EXPECTED_RESULT")
})

test_that("l", {
  # tests for the property `l` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`l`, "EXPECTED_RESULT")
})

test_that("s", {
  # tests for the property `s` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`s`, "EXPECTED_RESULT")
})

test_that("t", {
  # tests for the property `t` (character)

  # uncomment below to test the property
  #expect_equal(model.instance$`t`, "EXPECTED_RESULT")
})
