#' AZMet API
#'
#' REST API for the Arizona Meteorological Network (AZMet)
#'
#' The version of the OpenAPI document: 1.0
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Daily operations
#' @description DailyApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ v1_observations_daily_get } \emph{ Return daily direct and derived observations for all stations for the latest available day. }
#' Returns available daily direct and derived observations for all stations for the latest available day.
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse200} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | An array of all direct and derived observations for all stations.
#'
#' \item return type : InlineResponse200
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ v1_observations_daily_station_id_date_time_start_get } \emph{ Return daily direct and derived observations for a specific station and a specific date. }
#' Returns available daily direct and derived observations for a specific station and a specific date.
#'
#' \itemize{
#' \item \emph{ @param } station_id character
#' \item \emph{ @param } date_time_start character
#' \item \emph{ @returnType } \link{InlineResponse2001} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Available daily direct and derived observations for the requested station and date.
#'
#' \item return type : InlineResponse2001
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ v1_observations_daily_station_id_date_time_start_time_interval_get } \emph{ Return available daily direct and derived observations for a station over a time interval from a date. }
#' Returns available daily direct and derived observations for a specific station over a time interval from a specific date.
#'
#' \itemize{
#' \item \emph{ @param } station_id character
#' \item \emph{ @param } date_time_start character
#' \item \emph{ @param } time_interval character
#' \item \emph{ @returnType } \link{InlineResponse2001} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Available daily direct and derived observations for a specific station over a time interval from a specific date
#'
#' \item return type : InlineResponse2001
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ v1_observations_daily_station_id_get } \emph{ Return daily direct and derived observations for a specific station. }
#' Returns available daily direct and derived observations for a specific station.
#'
#' \itemize{
#' \item \emph{ @param } station_id character
#' \item \emph{ @returnType } \link{InlineResponse2001} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Successful return of daily direct and derived observations for a specific station.
#'
#' \item return type : InlineResponse2001
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  v1_observations_daily_get  ####################
#'
#' library(azmet)
#'
#' #Return daily direct and derived observations for all stations for the latest available day.
#' api_instance <- DailyApi$new()
#'
#' result <- tryCatch(
#'              
#'              # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#'              # api_instance$v1_observations_daily_get(data_file = "result.txt"),
#'              
#'              
#'              api_instance$v1_observations_daily_get(),
#'              ApiException = function(ex) ex
#'           )
#' # In case of error, print the error object
#' if (!is.null(result$ApiException)) {
#'   print("Exception occurs when calling `v1_observations_daily_get`:")
#'   dput(result$ApiException$toString())
#'   
#'   # error object
#'   dput(result$ApiException$error_object$toJSONString())
#'   
#' } else {
#'   # deserialized response object
#'   print("The response is ...")
#'   dput(result$toString())
#' }
#'
#'
#'
#' ####################  v1_observations_daily_station_id_date_time_start_get  ####################
#'
#' library(azmet)
#' var_station_id <- "station_id_example" # character | ID of station
#' var_date_time_start <- "date_time_start_example" # character | Date and time of data request start
#'
#' #Return daily direct and derived observations for a specific station and a specific date.
#' api_instance <- DailyApi$new()
#'
#' result <- tryCatch(
#'              
#'              # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#'              # api_instance$v1_observations_daily_station_id_date_time_start_get(var_station_id, var_date_time_start, data_file = "result.txt"),
#'              
#'              
#'              api_instance$v1_observations_daily_station_id_date_time_start_get(var_station_id, var_date_time_start),
#'              ApiException = function(ex) ex
#'           )
#' # In case of error, print the error object
#' if (!is.null(result$ApiException)) {
#'   print("Exception occurs when calling `v1_observations_daily_station_id_date_time_start_get`:")
#'   dput(result$ApiException$toString())
#'   
#'   # error object
#'   dput(result$ApiException$error_object$toJSONString())
#'   
#' } else {
#'   # deserialized response object
#'   print("The response is ...")
#'   dput(result$toString())
#' }
#'
#'
#'
#' ####################  v1_observations_daily_station_id_date_time_start_time_interval_get  ####################
#'
#' library(azmet)
#' var_station_id <- "station_id_example" # character | ID of station
#' var_date_time_start <- "date_time_start_example" # character | Datetime to start the interval
#' var_time_interval <- "time_interval_example" # character | The requested time interval
#'
#' #Return available daily direct and derived observations for a station over a time interval from a date.
#' api_instance <- DailyApi$new()
#'
#' result <- tryCatch(
#'              
#'              # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#'              # api_instance$v1_observations_daily_station_id_date_time_start_time_interval_get(var_station_id, var_date_time_start, var_time_interval, data_file = "result.txt"),
#'              
#'              
#'              api_instance$v1_observations_daily_station_id_date_time_start_time_interval_get(var_station_id, var_date_time_start, var_time_interval),
#'              ApiException = function(ex) ex
#'           )
#' # In case of error, print the error object
#' if (!is.null(result$ApiException)) {
#'   print("Exception occurs when calling `v1_observations_daily_station_id_date_time_start_time_interval_get`:")
#'   dput(result$ApiException$toString())
#'   
#'   # error object
#'   dput(result$ApiException$error_object$toJSONString())
#'   
#' } else {
#'   # deserialized response object
#'   print("The response is ...")
#'   dput(result$toString())
#' }
#'
#'
#'
#' ####################  v1_observations_daily_station_id_get  ####################
#'
#' library(azmet)
#' var_station_id <- "station_id_example" # character | ID of station
#'
#' #Return daily direct and derived observations for a specific station.
#' api_instance <- DailyApi$new()
#'
#' result <- tryCatch(
#'              
#'              # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#'              # api_instance$v1_observations_daily_station_id_get(var_station_id, data_file = "result.txt"),
#'              
#'              
#'              api_instance$v1_observations_daily_station_id_get(var_station_id),
#'              ApiException = function(ex) ex
#'           )
#' # In case of error, print the error object
#' if (!is.null(result$ApiException)) {
#'   print("Exception occurs when calling `v1_observations_daily_station_id_get`:")
#'   dput(result$ApiException$toString())
#'   
#'   # error object
#'   dput(result$ApiException$error_object$toJSONString())
#'   
#' } else {
#'   # deserialized response object
#'   print("The response is ...")
#'   dput(result$toString())
#' }
#'
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @importFrom rlang abort
#' @export
DailyApi <- R6::R6Class(
  "DailyApi",
  public = list(
    api_client = NULL,
    #' Initialize a new DailyApi.
    #'
    #' @description
    #' Initialize a new DailyApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Return daily direct and derived observations for all stations for the latest available day.
    #'
    #' @description
    #' Return daily direct and derived observations for all stations for the latest available day.
    #'
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return InlineResponse200
    #' @export
    v1_observations_daily_get = function(data_file = NULL, ...) {
      local_var_response <- self$v1_observations_daily_get_with_http_info(data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Return daily direct and derived observations for all stations for the latest available day.
    #'
    #' @description
    #' Return daily direct and derived observations for all stations for the latest available day.
    #'
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (InlineResponse200) with additional information such as HTTP status code, headers
    #' @export
    v1_observations_daily_get_with_http_info = function(data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      local_var_url_path <- "/v1/observations/daily"

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
            write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "InlineResponse200", loadNamespace("azmet")),
          error = function(e) {
             rlang::abort(message = "Failed to deserialize response",
                          .subclass = "ApiException",
                          ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- paste("Server returned ", local_var_resp$status_code, " response status code.")
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api client exception encountered."
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api server exception encountered."
        }
        rlang::abort(message = error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      }
    },
    #' Return daily direct and derived observations for a specific station and a specific date.
    #'
    #' @description
    #' Return daily direct and derived observations for a specific station and a specific date.
    #'
    #' @param station_id ID of station
    #' @param date_time_start Date and time of data request start
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return InlineResponse2001
    #' @export
    v1_observations_daily_station_id_date_time_start_get = function(station_id, date_time_start, data_file = NULL, ...) {
      local_var_response <- self$v1_observations_daily_station_id_date_time_start_get_with_http_info(station_id, date_time_start, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Return daily direct and derived observations for a specific station and a specific date.
    #'
    #' @description
    #' Return daily direct and derived observations for a specific station and a specific date.
    #'
    #' @param station_id ID of station
    #' @param date_time_start Date and time of data request start
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (InlineResponse2001) with additional information such as HTTP status code, headers
    #' @export
    v1_observations_daily_station_id_date_time_start_get_with_http_info = function(station_id, date_time_start, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`station_id`)) {
        rlang::abort(message = "Missing required parameter `station_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `station_id`."))
      }

      if (missing(`date_time_start`)) {
        rlang::abort(message = "Missing required parameter `date_time_start`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `date_time_start`."))
      }



      local_var_url_path <- "/v1/observations/daily/{stationID}/{dateTimeStart}"
      if (!missing(`station_id`)) {
        local_var_url_path <- gsub(paste0("\\{", "stationID", "\\}"), URLencode(as.character(`station_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`date_time_start`)) {
        local_var_url_path <- gsub(paste0("\\{", "dateTimeStart", "\\}"), URLencode(as.character(`date_time_start`), reserved = TRUE), local_var_url_path)
      }


      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
            write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "InlineResponse2001", loadNamespace("azmet")),
          error = function(e) {
             rlang::abort(message = "Failed to deserialize response",
                          .subclass = "ApiException",
                          ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- paste("Server returned ", local_var_resp$status_code, " response status code.")
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api client exception encountered."
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api server exception encountered."
        }
        rlang::abort(message = error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      }
    },
    #' Return available daily direct and derived observations for a station over a time interval from a date.
    #'
    #' @description
    #' Return available daily direct and derived observations for a station over a time interval from a date.
    #'
    #' @param station_id ID of station
    #' @param date_time_start Datetime to start the interval
    #' @param time_interval The requested time interval
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return InlineResponse2001
    #' @export
    v1_observations_daily_station_id_date_time_start_time_interval_get = function(station_id, date_time_start, time_interval, data_file = NULL, ...) {
      local_var_response <- self$v1_observations_daily_station_id_date_time_start_time_interval_get_with_http_info(station_id, date_time_start, time_interval, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Return available daily direct and derived observations for a station over a time interval from a date.
    #'
    #' @description
    #' Return available daily direct and derived observations for a station over a time interval from a date.
    #'
    #' @param station_id ID of station
    #' @param date_time_start Datetime to start the interval
    #' @param time_interval The requested time interval
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (InlineResponse2001) with additional information such as HTTP status code, headers
    #' @export
    v1_observations_daily_station_id_date_time_start_time_interval_get_with_http_info = function(station_id, date_time_start, time_interval, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`station_id`)) {
        rlang::abort(message = "Missing required parameter `station_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `station_id`."))
      }

      if (missing(`date_time_start`)) {
        rlang::abort(message = "Missing required parameter `date_time_start`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `date_time_start`."))
      }

      if (missing(`time_interval`)) {
        rlang::abort(message = "Missing required parameter `time_interval`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `time_interval`."))
      }




      local_var_url_path <- "/v1/observations/daily/{stationID}/{dateTimeStart}/{timeInterval}"
      if (!missing(`station_id`)) {
        local_var_url_path <- gsub(paste0("\\{", "stationID", "\\}"), URLencode(as.character(`station_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`date_time_start`)) {
        local_var_url_path <- gsub(paste0("\\{", "dateTimeStart", "\\}"), URLencode(as.character(`date_time_start`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`time_interval`)) {
        local_var_url_path <- gsub(paste0("\\{", "timeInterval", "\\}"), URLencode(as.character(`time_interval`), reserved = TRUE), local_var_url_path)
      }


      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
            write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "InlineResponse2001", loadNamespace("azmet")),
          error = function(e) {
             rlang::abort(message = "Failed to deserialize response",
                          .subclass = "ApiException",
                          ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- paste("Server returned ", local_var_resp$status_code, " response status code.")
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api client exception encountered."
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api server exception encountered."
        }
        rlang::abort(message = error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      }
    },
    #' Return daily direct and derived observations for a specific station.
    #'
    #' @description
    #' Return daily direct and derived observations for a specific station.
    #'
    #' @param station_id ID of station
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return InlineResponse2001
    #' @export
    v1_observations_daily_station_id_get = function(station_id, data_file = NULL, ...) {
      local_var_response <- self$v1_observations_daily_station_id_get_with_http_info(station_id, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Return daily direct and derived observations for a specific station.
    #'
    #' @description
    #' Return daily direct and derived observations for a specific station.
    #'
    #' @param station_id ID of station
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (InlineResponse2001) with additional information such as HTTP status code, headers
    #' @export
    v1_observations_daily_station_id_get_with_http_info = function(station_id, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`station_id`)) {
        rlang::abort(message = "Missing required parameter `station_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `station_id`."))
      }


      local_var_url_path <- "/v1/observations/daily/{stationID}"
      if (!missing(`station_id`)) {
        local_var_url_path <- gsub(paste0("\\{", "stationID", "\\}"), URLencode(as.character(`station_id`), reserved = TRUE), local_var_url_path)
      }


      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
            write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "InlineResponse2001", loadNamespace("azmet")),
          error = function(e) {
             rlang::abort(message = "Failed to deserialize response",
                          .subclass = "ApiException",
                          ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- paste("Server returned ", local_var_resp$status_code, " response status code.")
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api client exception encountered."
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api server exception encountered."
        }
        rlang::abort(message = error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      }
    }
  )
)
