#' AZMet API
#'
#' REST API for the Arizona Meteorological Network (AZMet)
#'
#' The version of the OpenAPI document: 1.0
#' Generated by: https://openapi-generator.tech
#'
#' @docType class
#' @title Hueto operations
#' @description HuetoApi
#' @format An \code{R6Class} generator object
#' @field api_client Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ v1_observations_hueto_get } \emph{ Accumulated heat units and evapotranspiration for all stations from January 1 current year. }
#' Returns accumulated heat units and evapotranspiration for all stations from the start of the current year.
#'
#' \itemize{
#' \item \emph{ @returnType } \link{InlineResponse2005} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Accumulated heat units and evapotranspiration for all stations from the start of the current year.
#'
#' \item return type : InlineResponse2005
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ v1_observations_hueto_station_id_date_time_start_get } \emph{ Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time to current date. }
#' Returns accumulated heat units and evapotranspiration for one (or all \"*\") station(s) from the given start date and time to current date.
#'
#' \itemize{
#' \item \emph{ @param } station_id character
#' \item \emph{ @param } date_time_start character
#' \item \emph{ @returnType } \link{InlineResponse2006} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Auto generated using Swagger Inspector
#'
#' \item return type : InlineResponse2006
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ v1_observations_hueto_station_id_date_time_start_time_interval_get } \emph{ Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time over a given time interval. }
#' Returns accumulated heat units and evapotranspiration for one (or all \"*\") station(s) from the given start date and timeover a given time interval.
#'
#' \itemize{
#' \item \emph{ @param } station_id character
#' \item \emph{ @param } date_time_start character
#' \item \emph{ @param } time_interval character
#' \item \emph{ @returnType } \link{InlineResponse2006} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Auto generated using Swagger Inspector
#'
#' \item return type : InlineResponse2006
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' \strong{ v1_observations_hueto_station_id_get } \emph{ Accumulated heat units and evapotranspiration for one station from January 1 current year. }
#' Returns accumulated heat units and evapotranspiration for one station from the start of the current year.
#'
#' \itemize{
#' \item \emph{ @param } station_id character
#' \item \emph{ @returnType } \link{InlineResponse2006} \cr
#'
#' \item On encountering errors, an error of subclass ApiException will be thrown.
#'
#' \item status code : 200 | Accumulated heat units and evapotranspiration for one station from the start of the current year.
#'
#' \item return type : InlineResponse2006
#' \item response headers :
#'
#' \tabular{ll}{
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  v1_observations_hueto_get  ####################
#'
#' library(azmet)
#'
#' #Accumulated heat units and evapotranspiration for all stations from January 1 current year.
#' api_instance <- HuetoApi$new()
#'
#' result <- tryCatch(
#'              
#'              # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#'              # api_instance$v1_observations_hueto_get(data_file = "result.txt"),
#'              
#'              
#'              api_instance$v1_observations_hueto_get(),
#'              ApiException = function(ex) ex
#'           )
#' # In case of error, print the error object
#' if (!is.null(result$ApiException)) {
#'   print("Exception occurs when calling `v1_observations_hueto_get`:")
#'   dput(result$ApiException$toString())
#'   
#'   # error object
#'   dput(result$ApiException$error_object$toJSONString())
#'   
#' } else {
#'   # deserialized response object
#'   print("The response is ...")
#'   dput(result$toString())
#' }
#'
#'
#'
#' ####################  v1_observations_hueto_station_id_date_time_start_get  ####################
#'
#' library(azmet)
#' var_station_id <- "station_id_example" # character | ID of station
#' var_date_time_start <- "date_time_start_example" # character | Date and time of data request start
#'
#' #Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time to current date.
#' api_instance <- HuetoApi$new()
#'
#' result <- tryCatch(
#'              
#'              # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#'              # api_instance$v1_observations_hueto_station_id_date_time_start_get(var_station_id, var_date_time_start, data_file = "result.txt"),
#'              
#'              
#'              api_instance$v1_observations_hueto_station_id_date_time_start_get(var_station_id, var_date_time_start),
#'              ApiException = function(ex) ex
#'           )
#' # In case of error, print the error object
#' if (!is.null(result$ApiException)) {
#'   print("Exception occurs when calling `v1_observations_hueto_station_id_date_time_start_get`:")
#'   dput(result$ApiException$toString())
#'   
#'   # error object
#'   dput(result$ApiException$error_object$toJSONString())
#'   
#' } else {
#'   # deserialized response object
#'   print("The response is ...")
#'   dput(result$toString())
#' }
#'
#'
#'
#' ####################  v1_observations_hueto_station_id_date_time_start_time_interval_get  ####################
#'
#' library(azmet)
#' var_station_id <- "station_id_example" # character | ID of station
#' var_date_time_start <- "date_time_start_example" # character | Date and time of data request start
#' var_time_interval <- "time_interval_example" # character | The requested time interval
#'
#' #Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time over a given time interval.
#' api_instance <- HuetoApi$new()
#'
#' result <- tryCatch(
#'              
#'              # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#'              # api_instance$v1_observations_hueto_station_id_date_time_start_time_interval_get(var_station_id, var_date_time_start, var_time_interval, data_file = "result.txt"),
#'              
#'              
#'              api_instance$v1_observations_hueto_station_id_date_time_start_time_interval_get(var_station_id, var_date_time_start, var_time_interval),
#'              ApiException = function(ex) ex
#'           )
#' # In case of error, print the error object
#' if (!is.null(result$ApiException)) {
#'   print("Exception occurs when calling `v1_observations_hueto_station_id_date_time_start_time_interval_get`:")
#'   dput(result$ApiException$toString())
#'   
#'   # error object
#'   dput(result$ApiException$error_object$toJSONString())
#'   
#' } else {
#'   # deserialized response object
#'   print("The response is ...")
#'   dput(result$toString())
#' }
#'
#'
#'
#' ####################  v1_observations_hueto_station_id_get  ####################
#'
#' library(azmet)
#' var_station_id <- "station_id_example" # character | ID of station
#'
#' #Accumulated heat units and evapotranspiration for one station from January 1 current year.
#' api_instance <- HuetoApi$new()
#'
#' result <- tryCatch(
#'              
#'              # to save the result into a file, simply add the optional `data_file` parameter, e.g.
#'              # api_instance$v1_observations_hueto_station_id_get(var_station_id, data_file = "result.txt"),
#'              
#'              
#'              api_instance$v1_observations_hueto_station_id_get(var_station_id),
#'              ApiException = function(ex) ex
#'           )
#' # In case of error, print the error object
#' if (!is.null(result$ApiException)) {
#'   print("Exception occurs when calling `v1_observations_hueto_station_id_get`:")
#'   dput(result$ApiException$toString())
#'   
#'   # error object
#'   dput(result$ApiException$error_object$toJSONString())
#'   
#' } else {
#'   # deserialized response object
#'   print("The response is ...")
#'   dput(result$toString())
#' }
#'
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @importFrom rlang abort
#' @export
HuetoApi <- R6::R6Class(
  "HuetoApi",
  public = list(
    api_client = NULL,
    #' Initialize a new HuetoApi.
    #'
    #' @description
    #' Initialize a new HuetoApi.
    #'
    #' @param api_client An instance of API client.
    #' @export
    initialize = function(api_client) {
      if (!missing(api_client)) {
        self$api_client <- api_client
      } else {
        self$api_client <- ApiClient$new()
      }
    },
    #' Accumulated heat units and evapotranspiration for all stations from January 1 current year.
    #'
    #' @description
    #' Accumulated heat units and evapotranspiration for all stations from January 1 current year.
    #'
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return InlineResponse2005
    #' @export
    v1_observations_hueto_get = function(data_file = NULL, ...) {
      local_var_response <- self$v1_observations_hueto_get_with_http_info(data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Accumulated heat units and evapotranspiration for all stations from January 1 current year.
    #'
    #' @description
    #' Accumulated heat units and evapotranspiration for all stations from January 1 current year.
    #'
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (InlineResponse2005) with additional information such as HTTP status code, headers
    #' @export
    v1_observations_hueto_get_with_http_info = function(data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      local_var_url_path <- "/v1/observations/hueto"

      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
            write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "InlineResponse2005", loadNamespace("azmet")),
          error = function(e) {
             rlang::abort(message = "Failed to deserialize response",
                          .subclass = "ApiException",
                          ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- paste("Server returned ", local_var_resp$status_code, " response status code.")
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api client exception encountered."
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api server exception encountered."
        }
        rlang::abort(message = error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      }
    },
    #' Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time to current date.
    #'
    #' @description
    #' Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time to current date.
    #'
    #' @param station_id ID of station
    #' @param date_time_start Date and time of data request start
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return InlineResponse2006
    #' @export
    v1_observations_hueto_station_id_date_time_start_get = function(station_id, date_time_start, data_file = NULL, ...) {
      local_var_response <- self$v1_observations_hueto_station_id_date_time_start_get_with_http_info(station_id, date_time_start, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time to current date.
    #'
    #' @description
    #' Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time to current date.
    #'
    #' @param station_id ID of station
    #' @param date_time_start Date and time of data request start
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (InlineResponse2006) with additional information such as HTTP status code, headers
    #' @export
    v1_observations_hueto_station_id_date_time_start_get_with_http_info = function(station_id, date_time_start, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`station_id`)) {
        rlang::abort(message = "Missing required parameter `station_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `station_id`."))
      }

      if (missing(`date_time_start`)) {
        rlang::abort(message = "Missing required parameter `date_time_start`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `date_time_start`."))
      }



      local_var_url_path <- "/v1/observations/hueto/{stationID}/{dateTimeStart}"
      if (!missing(`station_id`)) {
        local_var_url_path <- gsub(paste0("\\{", "stationID", "\\}"), URLencode(as.character(`station_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`date_time_start`)) {
        local_var_url_path <- gsub(paste0("\\{", "dateTimeStart", "\\}"), URLencode(as.character(`date_time_start`), reserved = TRUE), local_var_url_path)
      }


      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
            write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "InlineResponse2006", loadNamespace("azmet")),
          error = function(e) {
             rlang::abort(message = "Failed to deserialize response",
                          .subclass = "ApiException",
                          ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- paste("Server returned ", local_var_resp$status_code, " response status code.")
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api client exception encountered."
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api server exception encountered."
        }
        rlang::abort(message = error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      }
    },
    #' Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time over a given time interval.
    #'
    #' @description
    #' Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time over a given time interval.
    #'
    #' @param station_id ID of station
    #' @param date_time_start Date and time of data request start
    #' @param time_interval The requested time interval
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return InlineResponse2006
    #' @export
    v1_observations_hueto_station_id_date_time_start_time_interval_get = function(station_id, date_time_start, time_interval, data_file = NULL, ...) {
      local_var_response <- self$v1_observations_hueto_station_id_date_time_start_time_interval_get_with_http_info(station_id, date_time_start, time_interval, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time over a given time interval.
    #'
    #' @description
    #' Accumulated heat units and evapotranspiration for one (or all) station(s) from the given start date and time over a given time interval.
    #'
    #' @param station_id ID of station
    #' @param date_time_start Date and time of data request start
    #' @param time_interval The requested time interval
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (InlineResponse2006) with additional information such as HTTP status code, headers
    #' @export
    v1_observations_hueto_station_id_date_time_start_time_interval_get_with_http_info = function(station_id, date_time_start, time_interval, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`station_id`)) {
        rlang::abort(message = "Missing required parameter `station_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `station_id`."))
      }

      if (missing(`date_time_start`)) {
        rlang::abort(message = "Missing required parameter `date_time_start`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `date_time_start`."))
      }

      if (missing(`time_interval`)) {
        rlang::abort(message = "Missing required parameter `time_interval`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `time_interval`."))
      }




      local_var_url_path <- "/v1/observations/hueto/{stationID}/{dateTimeStart}/{timeInterval}"
      if (!missing(`station_id`)) {
        local_var_url_path <- gsub(paste0("\\{", "stationID", "\\}"), URLencode(as.character(`station_id`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`date_time_start`)) {
        local_var_url_path <- gsub(paste0("\\{", "dateTimeStart", "\\}"), URLencode(as.character(`date_time_start`), reserved = TRUE), local_var_url_path)
      }

      if (!missing(`time_interval`)) {
        local_var_url_path <- gsub(paste0("\\{", "timeInterval", "\\}"), URLencode(as.character(`time_interval`), reserved = TRUE), local_var_url_path)
      }


      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
            write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "InlineResponse2006", loadNamespace("azmet")),
          error = function(e) {
             rlang::abort(message = "Failed to deserialize response",
                          .subclass = "ApiException",
                          ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- paste("Server returned ", local_var_resp$status_code, " response status code.")
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api client exception encountered."
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api server exception encountered."
        }
        rlang::abort(message = error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      }
    },
    #' Accumulated heat units and evapotranspiration for one station from January 1 current year.
    #'
    #' @description
    #' Accumulated heat units and evapotranspiration for one station from January 1 current year.
    #'
    #' @param station_id ID of station
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return InlineResponse2006
    #' @export
    v1_observations_hueto_station_id_get = function(station_id, data_file = NULL, ...) {
      local_var_response <- self$v1_observations_hueto_station_id_get_with_http_info(station_id, data_file = data_file, ...)
      if (local_var_response$status_code >= 200 && local_var_response$status_code <= 299) {
        local_var_response$content
      } else if (local_var_response$status_code >= 300 && local_var_response$status_code <= 399) {
        local_var_response
      } else if (local_var_response$status_code >= 400 && local_var_response$status_code <= 499) {
        local_var_response
      } else if (local_var_response$status_code >= 500 && local_var_response$status_code <= 599) {
        local_var_response
      }
    },
    #' Accumulated heat units and evapotranspiration for one station from January 1 current year.
    #'
    #' @description
    #' Accumulated heat units and evapotranspiration for one station from January 1 current year.
    #'
    #' @param station_id ID of station
    #' @param data_file (optional) name of the data file to save the result
    #' @param ... Other optional arguments
    #' @return API response (InlineResponse2006) with additional information such as HTTP status code, headers
    #' @export
    v1_observations_hueto_station_id_get_with_http_info = function(station_id, data_file = NULL, ...) {
      args <- list(...)
      query_params <- list()
      header_params <- c()
      form_params <- list()
      file_params <- list()
      local_var_body <- NULL
      oauth_scopes <- NULL
      is_oauth <- FALSE

      if (missing(`station_id`)) {
        rlang::abort(message = "Missing required parameter `station_id`.",
                     .subclass = "ApiException",
                     ApiException = ApiException$new(status = 0,
                                                     reason = "Missing required parameter `station_id`."))
      }


      local_var_url_path <- "/v1/observations/hueto/{stationID}"
      if (!missing(`station_id`)) {
        local_var_url_path <- gsub(paste0("\\{", "stationID", "\\}"), URLencode(as.character(`station_id`), reserved = TRUE), local_var_url_path)
      }


      # The Accept request HTTP header
      local_var_accepts <- list("application/json")

      # The Content-Type representation header
      local_var_content_types <- list()

      local_var_resp <- self$api_client$CallApi(url = paste0(self$api_client$base_path, local_var_url_path),
                                 method = "GET",
                                 query_params = query_params,
                                 header_params = header_params,
                                 form_params = form_params,
                                 file_params = file_params,
                                 accepts = local_var_accepts,
                                 content_types = local_var_content_types,
                                 body = local_var_body,
                                 is_oauth = is_oauth,
                                 oauth_scopes = oauth_scopes,
                                 ...)

      if (local_var_resp$status_code >= 200 && local_var_resp$status_code <= 299) {
        # save response in a file
        if (!is.null(data_file)) {
            write(local_var_resp$response, data_file)
        }

        deserialized_resp_obj <- tryCatch(
          self$api_client$deserialize(local_var_resp$response, "InlineResponse2006", loadNamespace("azmet")),
          error = function(e) {
             rlang::abort(message = "Failed to deserialize response",
                          .subclass = "ApiException",
                          ApiException = ApiException$new(http_response = local_var_resp))
          }
        )
        local_var_resp$content <- deserialized_resp_obj
        local_var_resp
      } else if (local_var_resp$status_code >= 300 && local_var_resp$status_code <= 399) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- paste("Server returned ", local_var_resp$status_code, " response status code.")
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 400 && local_var_resp$status_code <= 499) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api client exception encountered."
        }
        rlang::abort(message = local_var_error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      } else if (local_var_resp$status_code >= 500 && local_var_resp$status_code <= 599) {
        local_var_error_msg <- local_var_resp$response
        if (local_var_error_msg == "") {
          local_var_error_msg <- "Api server exception encountered."
        }
        rlang::abort(message = error_msg,
                     .subclass = "ApiException",
                     ApiException = ApiException$new(http_response = local_var_resp))
      }
    }
  )
)
